/*
 * Reproductor sencillo.....................
 * Con vinculo hacia Youtube
 */
package metodos;

import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author erikj
 */
public class Visual extends javax.swing.JFrame {
private Reproductor reproductor;
private int cambio = 0;
private JFileChooser elegir;
private int PermisoParaAñadir = 0;

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
        elegir = new JFileChooser();
        Image icon = new ImageIcon(getClass().getResource("/imagenes/Icono.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelDeLaIzquierda = new javax.swing.JPanel();
        IzquierdaSuperior = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnYoutube = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        BtnSiguiente = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        BtnStop = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        PanelCentra = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        TituloPrincipal = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        ProgresoCancion = new javax.swing.JSlider();
        ImagenCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProgresoCancion2 = new javax.swing.JSlider();
        Pausar = new javax.swing.JPanel();
        Play = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LugarBoton = new javax.swing.JPanel();
        BtnPlay = new javax.swing.JButton();
        Pausa = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LugarBtn2 = new javax.swing.JPanel();
        BtnPausa_Continuar = new javax.swing.JButton();
        UltimoPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        ListadeReproduccion = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        PanelCentroBTN = new javax.swing.JPanel();
        BtnAtras = new javax.swing.JButton();
        UltimoBTN = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        Repetir = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        BtnRepetir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reproductor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        PanelDeLaIzquierda.setOpaque(false);
        PanelDeLaIzquierda.setLayout(new java.awt.GridLayout(3, 0));

        IzquierdaSuperior.setOpaque(false);
        IzquierdaSuperior.setLayout(new java.awt.GridLayout(3, 0));

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        IzquierdaSuperior.add(jPanel4);

        jPanel21.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Encuentra mas musica en:      ");
        jPanel21.add(jLabel2);

        BtnYoutube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/YtbNormal.png"))); // NOI18N
        BtnYoutube.setBorder(null);
        BtnYoutube.setBorderPainted(false);
        BtnYoutube.setContentAreaFilled(false);
        BtnYoutube.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/YtbMasGrande.png"))); // NOI18N
        BtnYoutube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYoutubeActionPerformed(evt);
            }
        });
        jPanel21.add(BtnYoutube);

        IzquierdaSuperior.add(jPanel21);

        jPanel25.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musica (1).png"))); // NOI18N
        jPanel25.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ondas-sonoras (1).png"))); // NOI18N
        jPanel25.add(jLabel4);

        IzquierdaSuperior.add(jPanel25);

        PanelDeLaIzquierda.add(IzquierdaSuperior);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(0, 3));

        jPanel15.setOpaque(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(3, 0));

        jPanel16.setOpaque(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.BorderLayout());

        BtnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/023-next.png"))); // NOI18N
        BtnSiguiente.setBorder(null);
        BtnSiguiente.setBorderPainted(false);
        BtnSiguiente.setContentAreaFilled(false);
        BtnSiguiente.setFocusPainted(false);
        BtnSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/023-next (1).png"))); // NOI18N
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });
        jPanel17.add(BtnSiguiente, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel17);

        jPanel5.add(jPanel14);

        PanelDeLaIzquierda.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(0, 3));

        jPanel7.setOpaque(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(3, 0));

        jPanel11.setOpaque(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.BorderLayout());

        BtnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reproductor-de-musica (1) (1).png"))); // NOI18N
        BtnStop.setBorder(null);
        BtnStop.setBorderPainted(false);
        BtnStop.setContentAreaFilled(false);
        BtnStop.setFocusPainted(false);
        BtnStop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reproductor-de-musica (1) (2).png"))); // NOI18N
        BtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStopActionPerformed(evt);
            }
        });
        jPanel12.add(BtnStop, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel12);

        jPanel13.setOpaque(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel13);

        jPanel6.add(jPanel8);

        jPanel9.setOpaque(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9);

        PanelDeLaIzquierda.add(jPanel6);

        jPanel1.add(PanelDeLaIzquierda);

        PanelCentra.setOpaque(false);
        PanelCentra.setLayout(new java.awt.GridLayout(3, 0));

        Titulo.setOpaque(false);
        Titulo.setLayout(new java.awt.GridLayout(3, 0));

        jPanel28.setOpaque(false);

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        Titulo.add(jPanel28);

        jPanel29.setOpaque(false);

        TituloPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        TituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel29.add(TituloPrincipal);

        Titulo.add(jPanel29);

        jPanel30.setOpaque(false);

        ProgresoCancion.setBackground(new java.awt.Color(255, 0, 51));
        ProgresoCancion.setPaintLabels(true);
        ProgresoCancion.setPaintTicks(true);
        ProgresoCancion.setSnapToTicks(true);
        ProgresoCancion.setValue(0);
        ProgresoCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProgresoCancion.setFocusable(false);
        jPanel30.add(ProgresoCancion);

        Titulo.add(jPanel30);

        PanelCentra.add(Titulo);

        ImagenCentral.setOpaque(false);
        ImagenCentral.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen Central.png"))); // NOI18N
        ImagenCentral.add(jLabel1, java.awt.BorderLayout.NORTH);

        ProgresoCancion2.setBackground(new java.awt.Color(0, 0, 0));
        ProgresoCancion2.setForeground(new java.awt.Color(255, 0, 0));
        ProgresoCancion2.setValue(0);
        ImagenCentral.add(ProgresoCancion2, java.awt.BorderLayout.SOUTH);

        PanelCentra.add(ImagenCentral);

        Pausar.setOpaque(false);
        Pausar.setLayout(new java.awt.GridLayout(0, 2));

        Play.setOpaque(false);
        Play.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        Play.add(jPanel2);

        LugarBoton.setOpaque(false);
        LugarBoton.setLayout(new java.awt.BorderLayout());

        BtnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Play-Boton.png"))); // NOI18N
        BtnPlay.setToolTipText("Play");
        BtnPlay.setBorder(null);
        BtnPlay.setBorderPainted(false);
        BtnPlay.setContentAreaFilled(false);
        BtnPlay.setEnabled(false);
        BtnPlay.setFocusPainted(false);
        BtnPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Play-Boton-Gran.png"))); // NOI18N
        BtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlayActionPerformed(evt);
            }
        });
        LugarBoton.add(BtnPlay, java.awt.BorderLayout.CENTER);

        Play.add(LugarBoton);

        Pausar.add(Play);

        Pausa.setOpaque(false);
        Pausa.setLayout(new java.awt.GridLayout(3, 0));

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        Pausa.add(jPanel3);

        LugarBtn2.setOpaque(false);
        LugarBtn2.setLayout(new java.awt.BorderLayout());

        BtnPausa_Continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pausa.png"))); // NOI18N
        BtnPausa_Continuar.setBorder(null);
        BtnPausa_Continuar.setBorderPainted(false);
        BtnPausa_Continuar.setContentAreaFilled(false);
        BtnPausa_Continuar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pausa-Mas.png"))); // NOI18N
        BtnPausa_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPausa_ContinuarActionPerformed(evt);
            }
        });
        LugarBtn2.add(BtnPausa_Continuar, java.awt.BorderLayout.CENTER);

        Pausa.add(LugarBtn2);

        Pausar.add(Pausa);

        PanelCentra.add(Pausar);

        jPanel1.add(PanelCentra);

        UltimoPanel.setOpaque(false);
        UltimoPanel.setLayout(new java.awt.GridLayout(3, 0));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(3, 0));

        jPanel26.setOpaque(false);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel26);

        jPanel27.setOpaque(false);
        jPanel27.setLayout(new java.awt.BorderLayout());

        ListadeReproduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir.png"))); // NOI18N
        ListadeReproduccion.setBorder(null);
        ListadeReproduccion.setBorderPainted(false);
        ListadeReproduccion.setContentAreaFilled(false);
        ListadeReproduccion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir-MG.png"))); // NOI18N
        ListadeReproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadeReproduccionActionPerformed(evt);
            }
        });
        jPanel27.add(ListadeReproduccion, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel27);

        UltimoPanel.add(jPanel10);

        BtnAnterior.setOpaque(false);
        BtnAnterior.setLayout(new java.awt.GridLayout(0, 3));

        jPanel18.setOpaque(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        BtnAnterior.add(jPanel18);

        jPanel19.setOpaque(false);
        jPanel19.setLayout(new java.awt.GridLayout(3, 0));

        jPanel20.setOpaque(false);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel20);

        PanelCentroBTN.setOpaque(false);
        PanelCentroBTN.setLayout(new java.awt.BorderLayout());

        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Anterior.png"))); // NOI18N
        BtnAtras.setBorder(null);
        BtnAtras.setBorderPainted(false);
        BtnAtras.setContentAreaFilled(false);
        BtnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Anterior-Masg.png"))); // NOI18N
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        PanelCentroBTN.add(BtnAtras, java.awt.BorderLayout.CENTER);

        jPanel19.add(PanelCentroBTN);

        BtnAnterior.add(jPanel19);

        UltimoPanel.add(BtnAnterior);

        UltimoBTN.setOpaque(false);
        UltimoBTN.setLayout(new java.awt.GridLayout(3, 0));

        jPanel22.setOpaque(false);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        UltimoBTN.add(jPanel22);

        Repetir.setOpaque(false);
        Repetir.setLayout(new java.awt.GridLayout(0, 3));

        jPanel23.setOpaque(false);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        Repetir.add(jPanel23);

        jPanel24.setOpaque(false);
        jPanel24.setLayout(new java.awt.BorderLayout());

        BtnRepetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Repetir.png"))); // NOI18N
        BtnRepetir.setBorder(null);
        BtnRepetir.setBorderPainted(false);
        BtnRepetir.setContentAreaFilled(false);
        BtnRepetir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RepetirGrande.png"))); // NOI18N
        BtnRepetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepetirActionPerformed(evt);
            }
        });
        jPanel24.add(BtnRepetir, java.awt.BorderLayout.CENTER);

        Repetir.add(jPanel24);

        UltimoBTN.add(Repetir);

        UltimoPanel.add(UltimoBTN);

        jPanel1.add(UltimoPanel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStopActionPerformed
    try {
        // Stop
        reproductor.Stop();
        PermisoParaAñadir = 0;
         System.out.println("Var: "+PermisoParaAñadir);
    } catch (Exception ex) {
        Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BtnStopActionPerformed

    private void BtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlayActionPerformed
    try {
        //Play
        reproductor.AbrirFichero();
        reproductor.Play();
        BtnPlay.setEnabled(false);
    } catch (Exception ex) {
        Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BtnPlayActionPerformed

    private void BtnPausa_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPausa_ContinuarActionPerformed
    try {
        if(cambio==0){
        // Pausa
        reproductor.Pausa();
        cambio+=1;
        }else{
         reproductor.Continuar();
         cambio-=1;
        }
    } catch (Exception ex) {
        Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BtnPausa_ContinuarActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        // Hacia adelante
        try {
        int validador=reproductor.CancionAnteriorOsiguiente(1);
        if(validador==1){
        }else{  
        reproductor.AbrirFichero();
        reproductor.Play();
        }
    } catch (Exception ex) {
        Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // Hacia atras
        int Validador=reproductor.CancionAnteriorOsiguiente(0);
   if(Validador==1){
        }else{
       try {
           //reproductor.Stop();
           reproductor.AbrirFichero();
           reproductor.Play();
       } catch (Exception ex) {
           Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
       }
        }
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnYoutubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYoutubeActionPerformed
        // Boton hacia Youtube
        reproductor.VinculoAURL();
    }//GEN-LAST:event_BtnYoutubeActionPerformed

    private void BtnRepetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepetirActionPerformed
        // Repetir
        reproductor.Repetir();
    }//GEN-LAST:event_BtnRepetirActionPerformed

    private void ListadeReproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadeReproduccionActionPerformed
        System.out.println("Var: "+PermisoParaAñadir);
        if(PermisoParaAñadir==0){
        elegir.setMultiSelectionEnabled(true);
        elegir.showOpenDialog(this);
        File[] files = elegir.getSelectedFiles();
        String Rutas [] = new String [files.length];
        String nombresDeLasCanciones [] = new String[files.length];
        //Se llenan ambos arreglos........
        for(int i=0;i<files.length;i++){
            System.out.println(i);
            Rutas[i]=files[i].toString();
            //Se envia el dato de la ruta para obtener el nombre del archivo y mandarlo a la etiqueta......
           // nombresDeLasCanciones[i]=reproductor.NombreDeLaRuta(Rutas[i]);//El retorno se guarda en el arreglo Nombre
            
        }//Instanciando para llamar a la clase Reproductor
        reproductor = new Reproductor(Rutas,TituloPrincipal,ProgresoCancion);
        PermisoParaAñadir = 1;
        BtnPlay.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"Detenga la pista actual para actualizar");
        }
    }//GEN-LAST:event_ListadeReproduccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnAnterior;
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnPausa_Continuar;
    private javax.swing.JButton BtnPlay;
    private javax.swing.JButton BtnRepetir;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JButton BtnStop;
    private javax.swing.JButton BtnYoutube;
    private javax.swing.JPanel ImagenCentral;
    private javax.swing.JPanel IzquierdaSuperior;
    private javax.swing.JButton ListadeReproduccion;
    private javax.swing.JPanel LugarBoton;
    private javax.swing.JPanel LugarBtn2;
    private javax.swing.JPanel PanelCentra;
    private javax.swing.JPanel PanelCentroBTN;
    private javax.swing.JPanel PanelDeLaIzquierda;
    private javax.swing.JPanel Pausa;
    private javax.swing.JPanel Pausar;
    private javax.swing.JPanel Play;
    private javax.swing.JSlider ProgresoCancion;
    private javax.swing.JSlider ProgresoCancion2;
    private javax.swing.JPanel Repetir;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel TituloPrincipal;
    private javax.swing.JPanel UltimoBTN;
    private javax.swing.JPanel UltimoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
